audio_bit_rate: '32'
calibration_mode: nocalib
constellation: QPSK
encoder_ip: 192.168.1.000
encoder_port: '0000'
fec: 3/4
frequency: 2409.75 / 27
gain: '-10'
mode: DVBS2
pcr_pts_delay: '800'
pluto_ip: 192.168.2.1
pluto_port: '7272'
provider: EA7KIR
service: Malaga
symbol_rate: '333'
